# taken from http://marshmallow_666.tripod.com/cgi-bin/
marshmallow_words = [
    u'aardvark', u'abacus', u'abundance', u'ache', u'acupuncture',
    u'airbrush', u'alien', u'anagram', u'angle', u'amazing', u'ankle',
    u'alphabet', u'antenna', u'aqua', u'asphalt', u'bacon', u'banana',
    u'bangles', u'banjo', u'bankrupt', u'bar', u'barracuda', u'basket',
    u'beluga', u'binder', u'birthday', u'bisect', u'blizzard', u'blunderbuss',
    u'boa', u'bog', u'bounce', u'broomstick', u'brought', u'bubble',
    u'budgie', u'bug', u'bug-a-boo', u'bugger', u'buff', u'burst', u'butter',
    u'buzz', u'cabana', u'cake', u'calculator', u'camera', u'candle',
    u'carnival', u'carpet', u'casino', u'cashew', u'catfish', u'ceiling',
    u'celery', u'chalet', u'chalk', u'chart', u'cheddar', u'chesterfield',
    u'chicken', u'chinchill', u'chit-chat', u'chocolate', u'chowder', u'coal',
    u'compass', u'compress', u'computer', u'conduct', u'contents', u'cookie',
    u'copper', u'corduroy', u'cow', u'cracker', u'crackle', u'croissant',
    u'cube', u'cupcake', u'curly', u'curtain', u'cushion', u'cuticle',
    u'daffodil', u'delicious', u'dictionary', u'dimple', u'ding-a-ling',
    u'disk', u'disco duck', u'dodo', u'dolphin', u'dong', u'donuts', u'dork',
    u'dracula', u'duct tape', u'effigy', u'egad', u'elastic', u'elephant',
    u'encasement', u'erosion', u'eyelash', u'fabulous', u'fantastic',
    u'feather', u'felafel', u'fetish', u'financial', u'finger', u'finite',
    u'fish', u'fizzle', u'fizzy', u'flame', u'flash', u'flavour', u'flick',
    u'flock', u'flour', u'flower', u'foamy', u'foot', u'fork', u'fritter',
    u'fudge', u'fungus', u'funny', u'fuse', u'fusion', u'fuzzy', u'garlic',
    u'gelatin', u'gelato', u'ghetto', u'glebe', u'glitter', u'glossy',
    u'groceries', u'goulashes', u'guacamole', u'gumdrop', u'haberdashery',
    u'hamster', u'happy', u'highlight', u'hippopotamus', u'hobbit', u'hold',
    u'hooligan', u'hydrant', u'icicles', u'idiot', u'implode', u'implosion',
    u'indeed', u'issue', u'itchy', u'jell-o', u'jewel', u'jump', u'kabob',
    u'kasai', u'kite', u'kiwi', u'ketchup', u'knob', u'laces', u'lacy',
    u'laughter', u'laundry', u'leaflet', u'legacy', u'leprechaun', u'lollypop',
    u'lumberjack', u'macadamia', u'magenta', u'magic', u'magnanimous',
    u'mango', u'margarine', u'massimo', u'mechanical', u'medicine', u'meh',
    u'melon', u'meow', u'mesh', u'metric', u'microphone', u'minnow', u'mitten',
    u'mozzarella', u'muck', u'mumble', u'mushy', u'mustache', u'nanimo',
    u'noodle', u'nostril', u'nuggets', u'oatmeal', u'oboe', u'o\'clock',
    u'octopus', u'odour', u'ointment', u'olive', u'optic', u'overhead', u'ox',
    u'oxen', u'pajamas', u'pancake', u'pansy', u'paper', u'paprika',
    u'parmesan', u'pasta', u'pattern', u'pecan', u'peek-a-boo', u'pen',
    u'pepper', u'pepperoni', u'peppermint', u'perfume', u'periwinkle',
    u'photograph', u'pie', u'pierce', u'pillow', u'pimple', u'pineapple',
    u'pistachio', u'plush', u'polish', u'pompom', u'poodle', u'pop',
    u'popsicle', u'prism', u'prospector', u'prosper', u'pudding', u'puppet',
    u'puzzle', u'queer', u'query', u'radish', u'rainbow', u'ribbon', u'rotate',
    u'salami', u'sandwich', u'saturday', u'saturn', u'saxophone', u'scissors',
    u'scooter', u'scrabbleship', u'scrunchie', u'scuffle', u'shadow',
    u'sickish', u'silicone', u'slippery', u'smash', u'smooch', u'snap',
    u'snooker', u'socks', u'soya', u'spaghett', u'sparkle', u'spatula',
    u'spiral', u'splurge', u'spoon', u'sprinkle', u'square', u'squiggle',
    u'squirrel', u'statistics', u'stuffing', u'sticky', u'sugar',
    u'sunshine', u'super', u'swirl', u'taffy', u'tangy', u'tape', u'tat',
    u'teepee', u'telephone', u'television', u'thinkable', u'tip', u'tofu',
    u'toga', u'trestle', u'tulip', u'turnip', u'turtle', u'tusks',
    u'ultimate', u'unicycle', u'unique', u'uranus', u'vegetable', u'waddle',
    u'waffle', u'wallet', u'walnut', u'wagon', u'window', u'whatever',
    u'whimsical', u'wobbly', u'yellow', u'zap', u'zebra', u'zigzag', u'zip',
    ]

# Taken from http://www.alphadictionary.com/articles/100_funniest_words.html
alpha_words = [u'Absquatulate',
u'Allegator',
u'Anencephalous',
u'Argle-bargle',
u'Batrachomyomachy',
u'Billingsgate',
u'Bloviate',
u'Blunderbuss',
u'Borborygm',
u'Boustrophedon',
u'Bowyang',
u'Brouhaha',
u'Bumbershoot',
u'Callipygian',
u'Canoodle',
u'Cantankerous',
u'Catercornered',
u'Cockalorum',
u'Cockamamie',
u'Codswallop',
u'Collop',
u'Collywobbles',
u'Comeuppance',
u'Crapulence',
u'Crudivore',
u'Discombobulate',
u'Donnybrook',
u'Doozy',
u'Dudgeon',
u'Ecdysiast',
u'Eructation',
u'Fard',
u'Fartlek',
u'Fatuous',
u'Filibuster',
u'Firkin',
u'Flibbertigibbet',
u'Flummox',
u'Folderol',
u'Formication',
u'Fuddy-duddy',
u'Furbelow',
u'Furphy',
u'Gaberlunzie',
u'Gardyloo',
u'Gastromancy',
u'Gazump',
u'Gobbledygook',
u'Gobemouche',
u'Godwottery',
u'Gongoozle',
u'Gonzo',
u'Goombah',
u'Hemidemisemiquaver',
u'Hobbledehoy',
u'Hocus-pocus',
u'Hoosegow',
u'Hootenanny',
u'Jackanapes',
u'Kerfuffle',
u'Klutz',
u'La-di-da',
u'Lagopodous',
u'Lickety-split',
u'Lickspittle',
u'Logorrhea',
u'Lollygag',
u'Malarkey',
u'Maverick',
u'Mollycoddle',
u'Mugwump',
u'Mumpsimus',
u'Namby-pamby',
u'Nincompoop',
u'Oocephalus',
u'Ornery',
u'Pandiculation',
u'Panjandrum',
u'Pettifogger',
u'Pratfall',
u'Quean',
u'Rambunctious',
u'Ranivorous',
u'Rigmarole',
u'Shenanigan',
u'Sialoquent',
u'Skedaddle',
u'Skullduggery',
u'Slangwhanger',
u'Smellfungus',
u'Snickersnee',
u'Snollygoster',
u'Snool',
u'Tatterdemalion',
u'Troglodyte',
u'Turdiform',
u'Unremacadamized',
u'Vomitory',
u'Wabbit',
u'Widdershins']


writers_words = [u'bamboozled',
u'bazinga',
u'bevy',
u'bifurcate',
u'bilirubin',
u'bobolink',
u'buccaneer',
u'bulgur',
u'bumfuzzle',
u'canoodle',
u'cantankerous',
u'carbuncle',
u'caterwaul',
u'cattywampus',
u'cheeky',
u'conniption',
u'coot',
u'didgeridoo',
u'dingy',
u'doodle',
u'doohickey',
u'eschew',
u'fiddledeedee',
u'finagle',
u'flanker',
u'floozy',
u'fungible',
u'girdle',
u'gobsmacked',
u'grog',
u'gumption',
u'gunky',
u'hitherto',
u'hoi polloi',
u'hornswoggle',
u'hullabaloo',
u'indubitably',
u'janky',
u'kahuna',
u'katydid',
u'kerplunk',
u'kinkajou',
u'knickers',
u'lackadaisical',
u'loopy',
u'manscape',
u'monkey',
u'mugwump',
u'namby-pamby',
u'noggin',
u'pantaloons',
u'passel',
u'persnickety',
u'popinjay',
u'prestidigitation',
u'proctor',
u'rapscallion',
u'rookery',
u'rumpus',
u'scootch',
u'scuttlebutt',
u'shebang',
u'Shih Tzu',
u'smegma',
u'snarky',
u'snuffle',
u'spelunker',
u'spork',
u'sprocket',
u'squeegee',
u'succubus',
u'tater',
u'tuber',
u'tuchis',
u'viper',
u'waddle',
u'walkabout',
u'wasabi',
u'weasel',
u'wenis',
u'whatnot',
u'wombat',
u'wonky',
u'zeitgeist']